#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lista3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CursosLista3")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAluno(Aluno instance);
    partial void UpdateAluno(Aluno instance);
    partial void DeleteAluno(Aluno instance);
    partial void InsertBoletim(Boletim instance);
    partial void UpdateBoletim(Boletim instance);
    partial void DeleteBoletim(Boletim instance);
    partial void InsertCurso(Curso instance);
    partial void UpdateCurso(Curso instance);
    partial void DeleteCurso(Curso instance);
    partial void InsertDisciplina(Disciplina instance);
    partial void UpdateDisciplina(Disciplina instance);
    partial void DeleteDisciplina(Disciplina instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::Lista3.Properties.Settings.Default.CursosLista3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Aluno> Alunos
		{
			get
			{
				return this.GetTable<Aluno>();
			}
		}
		
		public System.Data.Linq.Table<Boletim> Boletims
		{
			get
			{
				return this.GetTable<Boletim>();
			}
		}
		
		public System.Data.Linq.Table<Curso> Cursos
		{
			get
			{
				return this.GetTable<Curso>();
			}
		}
		
		public System.Data.Linq.Table<Disciplina> Disciplinas
		{
			get
			{
				return this.GetTable<Disciplina>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aluno")]
	public partial class Aluno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nome;
		
		private string _email;
		
		private string _fone;
		
		private System.Nullable<System.DateTime> _nascimento;
		
		private System.Nullable<int> _idCurso;
		
		private EntitySet<Boletim> _Boletims;
		
		private EntityRef<Curso> _Curso;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfoneChanging(string value);
    partial void OnfoneChanged();
    partial void OnnascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnnascimentoChanged();
    partial void OnidCursoChanging(System.Nullable<int> value);
    partial void OnidCursoChanged();
    #endregion
		
		public Aluno()
		{
			this._Boletims = new EntitySet<Boletim>(new Action<Boletim>(this.attach_Boletims), new Action<Boletim>(this.detach_Boletims));
			this._Curso = default(EntityRef<Curso>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50)")]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fone", DbType="VarChar(50)")]
		public string fone
		{
			get
			{
				return this._fone;
			}
			set
			{
				if ((this._fone != value))
				{
					this.OnfoneChanging(value);
					this.SendPropertyChanging();
					this._fone = value;
					this.SendPropertyChanged("fone");
					this.OnfoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nascimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> nascimento
		{
			get
			{
				return this._nascimento;
			}
			set
			{
				if ((this._nascimento != value))
				{
					this.OnnascimentoChanging(value);
					this.SendPropertyChanging();
					this._nascimento = value;
					this.SendPropertyChanged("nascimento");
					this.OnnascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCurso", DbType="Int")]
		public System.Nullable<int> idCurso
		{
			get
			{
				return this._idCurso;
			}
			set
			{
				if ((this._idCurso != value))
				{
					if (this._Curso.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCursoChanging(value);
					this.SendPropertyChanging();
					this._idCurso = value;
					this.SendPropertyChanged("idCurso");
					this.OnidCursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Boletim", Storage="_Boletims", ThisKey="id", OtherKey="idAluno")]
		public EntitySet<Boletim> Boletims
		{
			get
			{
				return this._Boletims;
			}
			set
			{
				this._Boletims.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Aluno", Storage="_Curso", ThisKey="idCurso", OtherKey="id", IsForeignKey=true)]
		public Curso Curso
		{
			get
			{
				return this._Curso.Entity;
			}
			set
			{
				Curso previousValue = this._Curso.Entity;
				if (((previousValue != value) 
							|| (this._Curso.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Curso.Entity = null;
						previousValue.Alunos.Remove(this);
					}
					this._Curso.Entity = value;
					if ((value != null))
					{
						value.Alunos.Add(this);
						this._idCurso = value.id;
					}
					else
					{
						this._idCurso = default(Nullable<int>);
					}
					this.SendPropertyChanged("Curso");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boletims(Boletim entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = this;
		}
		
		private void detach_Boletims(Boletim entity)
		{
			this.SendPropertyChanging();
			entity.Aluno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boletim")]
	public partial class Boletim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ano;
		
		private int _idAluno;
		
		private int _idDisciplina;
		
		private System.Nullable<int> _nota1;
		
		private System.Nullable<int> _nota2;
		
		private System.Nullable<int> _nota3;
		
		private System.Nullable<int> _nota4;
		
		private System.Nullable<int> _mediaParcial;
		
		private System.Nullable<int> _mediaFinal;
		
		private System.Nullable<int> _notaFinal;
		
		private EntityRef<Aluno> _Aluno;
		
		private EntityRef<Disciplina> _Disciplina;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnanoChanging(int value);
    partial void OnanoChanged();
    partial void OnidAlunoChanging(int value);
    partial void OnidAlunoChanged();
    partial void OnidDisciplinaChanging(int value);
    partial void OnidDisciplinaChanged();
    partial void Onnota1Changing(System.Nullable<int> value);
    partial void Onnota1Changed();
    partial void Onnota2Changing(System.Nullable<int> value);
    partial void Onnota2Changed();
    partial void Onnota3Changing(System.Nullable<int> value);
    partial void Onnota3Changed();
    partial void Onnota4Changing(System.Nullable<int> value);
    partial void Onnota4Changed();
    partial void OnmediaParcialChanging(System.Nullable<int> value);
    partial void OnmediaParcialChanged();
    partial void OnmediaFinalChanging(System.Nullable<int> value);
    partial void OnmediaFinalChanged();
    partial void OnnotaFinalChanging(System.Nullable<int> value);
    partial void OnnotaFinalChanged();
    #endregion
		
		public Boletim()
		{
			this._Aluno = default(EntityRef<Aluno>);
			this._Disciplina = default(EntityRef<Disciplina>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ano
		{
			get
			{
				return this._ano;
			}
			set
			{
				if ((this._ano != value))
				{
					this.OnanoChanging(value);
					this.SendPropertyChanging();
					this._ano = value;
					this.SendPropertyChanged("ano");
					this.OnanoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idAluno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idAluno
		{
			get
			{
				return this._idAluno;
			}
			set
			{
				if ((this._idAluno != value))
				{
					if (this._Aluno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidAlunoChanging(value);
					this.SendPropertyChanging();
					this._idAluno = value;
					this.SendPropertyChanged("idAluno");
					this.OnidAlunoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDisciplina", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idDisciplina
		{
			get
			{
				return this._idDisciplina;
			}
			set
			{
				if ((this._idDisciplina != value))
				{
					if (this._Disciplina.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDisciplinaChanging(value);
					this.SendPropertyChanging();
					this._idDisciplina = value;
					this.SendPropertyChanged("idDisciplina");
					this.OnidDisciplinaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota1", DbType="Int")]
		public System.Nullable<int> nota1
		{
			get
			{
				return this._nota1;
			}
			set
			{
				if ((this._nota1 != value))
				{
					this.Onnota1Changing(value);
					this.SendPropertyChanging();
					this._nota1 = value;
					this.SendPropertyChanged("nota1");
					this.Onnota1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota2", DbType="Int")]
		public System.Nullable<int> nota2
		{
			get
			{
				return this._nota2;
			}
			set
			{
				if ((this._nota2 != value))
				{
					this.Onnota2Changing(value);
					this.SendPropertyChanging();
					this._nota2 = value;
					this.SendPropertyChanged("nota2");
					this.Onnota2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota3", DbType="Int")]
		public System.Nullable<int> nota3
		{
			get
			{
				return this._nota3;
			}
			set
			{
				if ((this._nota3 != value))
				{
					this.Onnota3Changing(value);
					this.SendPropertyChanging();
					this._nota3 = value;
					this.SendPropertyChanged("nota3");
					this.Onnota3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota4", DbType="Int")]
		public System.Nullable<int> nota4
		{
			get
			{
				return this._nota4;
			}
			set
			{
				if ((this._nota4 != value))
				{
					this.Onnota4Changing(value);
					this.SendPropertyChanging();
					this._nota4 = value;
					this.SendPropertyChanged("nota4");
					this.Onnota4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediaParcial", DbType="Int")]
		public System.Nullable<int> mediaParcial
		{
			get
			{
				return this._mediaParcial;
			}
			set
			{
				if ((this._mediaParcial != value))
				{
					this.OnmediaParcialChanging(value);
					this.SendPropertyChanging();
					this._mediaParcial = value;
					this.SendPropertyChanged("mediaParcial");
					this.OnmediaParcialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mediaFinal", DbType="Int")]
		public System.Nullable<int> mediaFinal
		{
			get
			{
				return this._mediaFinal;
			}
			set
			{
				if ((this._mediaFinal != value))
				{
					this.OnmediaFinalChanging(value);
					this.SendPropertyChanging();
					this._mediaFinal = value;
					this.SendPropertyChanged("mediaFinal");
					this.OnmediaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notaFinal", DbType="Int")]
		public System.Nullable<int> notaFinal
		{
			get
			{
				return this._notaFinal;
			}
			set
			{
				if ((this._notaFinal != value))
				{
					this.OnnotaFinalChanging(value);
					this.SendPropertyChanging();
					this._notaFinal = value;
					this.SendPropertyChanged("notaFinal");
					this.OnnotaFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aluno_Boletim", Storage="_Aluno", ThisKey="idAluno", OtherKey="id", IsForeignKey=true)]
		public Aluno Aluno
		{
			get
			{
				return this._Aluno.Entity;
			}
			set
			{
				Aluno previousValue = this._Aluno.Entity;
				if (((previousValue != value) 
							|| (this._Aluno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Aluno.Entity = null;
						previousValue.Boletims.Remove(this);
					}
					this._Aluno.Entity = value;
					if ((value != null))
					{
						value.Boletims.Add(this);
						this._idAluno = value.id;
					}
					else
					{
						this._idAluno = default(int);
					}
					this.SendPropertyChanged("Aluno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplina_Boletim", Storage="_Disciplina", ThisKey="idDisciplina", OtherKey="id", IsForeignKey=true)]
		public Disciplina Disciplina
		{
			get
			{
				return this._Disciplina.Entity;
			}
			set
			{
				Disciplina previousValue = this._Disciplina.Entity;
				if (((previousValue != value) 
							|| (this._Disciplina.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Disciplina.Entity = null;
						previousValue.Boletims.Remove(this);
					}
					this._Disciplina.Entity = value;
					if ((value != null))
					{
						value.Boletims.Add(this);
						this._idDisciplina = value.id;
					}
					else
					{
						this._idDisciplina = default(int);
					}
					this.SendPropertyChanged("Disciplina");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Curso")]
	public partial class Curso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descricao;
		
		private EntitySet<Aluno> _Alunos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public Curso()
		{
			this._Alunos = new EntitySet<Aluno>(new Action<Aluno>(this.attach_Alunos), new Action<Aluno>(this.detach_Alunos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(50)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Curso_Aluno", Storage="_Alunos", ThisKey="id", OtherKey="idCurso")]
		public EntitySet<Aluno> Alunos
		{
			get
			{
				return this._Alunos;
			}
			set
			{
				this._Alunos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alunos(Aluno entity)
		{
			this.SendPropertyChanging();
			entity.Curso = this;
		}
		
		private void detach_Alunos(Aluno entity)
		{
			this.SendPropertyChanging();
			entity.Curso = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Disciplina")]
	public partial class Disciplina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descricao;
		
		private EntitySet<Boletim> _Boletims;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public Disciplina()
		{
			this._Boletims = new EntitySet<Boletim>(new Action<Boletim>(this.attach_Boletims), new Action<Boletim>(this.detach_Boletims));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(50)")]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Disciplina_Boletim", Storage="_Boletims", ThisKey="id", OtherKey="idDisciplina")]
		public EntitySet<Boletim> Boletims
		{
			get
			{
				return this._Boletims;
			}
			set
			{
				this._Boletims.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boletims(Boletim entity)
		{
			this.SendPropertyChanging();
			entity.Disciplina = this;
		}
		
		private void detach_Boletims(Boletim entity)
		{
			this.SendPropertyChanging();
			entity.Disciplina = null;
		}
	}
}
#pragma warning restore 1591
